### ISSUE TITLE
config.yaml

### ISSUE THREAD

**Issue by DK223** [DixonCider/TCRI-Benchmark#1]
hello，i searched the config.yaml file and cound't find it in the code. Was it forgotten to upload? Or I have to generate it myself?

**Comment by jybai** [comment]
Hi @DK223, thanks for reaching out. The config files are located inside individual pretrained model directories in `./pretrained_models`. But first you will have to combine the sharded, pretrained models first by following the instruction in README. Let me know if anything else isn't clear. Thanks!

**Comment by DK223** [comment]
Thanks!
